// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
    API: {
        GraphQL: {
          endpoint: 'https://zzf363g765hvnfx5p7arpvswaq.appsync-api.eu-central-1.amazonaws.com/graphql',
          region: 'eu-central-1',
          defaultAuthMode: 'apiKey',
          apiKey: 'da2-xv7u5a2xunbk3p4i3rjlp2fki4'
        }
    }
};

export default config;